#!/bin/bash
SYSROOT="/Volumes/T9/ryan-homedir/devel/wario/oasis-sysroot"
INCS="-I$SYSROOT/usr/include/gtk-2.0 -I$SYSROOT/usr/lib/gtk-2.0/include -I$SYSROOT/usr/include/atk-1.0 -I$SYSROOT/usr/include/cairo -I$SYSROOT/usr/include/gdk-pixbuf-2.0 -I$SYSROOT/usr/include/pango-1.0 -I$SYSROOT/usr/include/glib-2.0 -I$SYSROOT/usr/include/glib-2.0/include -I$SYSROOT/usr/include/pixman-1 -I$SYSROOT/usr/include/freetype2 -I$SYSROOT/usr/include/harfbuzz -I$SYSROOT/usr/include/libpng16 -I$SYSROOT/usr/include"
LIBS="-L$SYSROOT/usr/lib -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lglib-2.0 -lX11 -lxcb -lxcb-shm -lxcb-render -lpixman-1 -lXdamage -lXfixes -lresolv -lXinerama -lXau -lXdmcp"

case "$*" in
  *cflags*)
    echo "$INCS"
    ;;
  *libs*)
    echo "$LIBS"
    ;;
  *)
    echo "pkg-config wrapper: unhandled query: $*" >&2
    exit 1
    ;;
esac
